version: '3'
services:
  famcy:
    image: nexuni/famcy:1.0.beta.5
    command: 
      - bash
      - -c 
      - |
        cd /app/.local/share/famcy/dev && . venv/bin/activate && cd console
        pip3 install -r requirements.txt
        redis-server &
        cd /app/.local/share/famcy/dev/venv/lib/python3.7/site-packages 
        gunicorn -b 0.0.0.0:8888 Famcy.wsgi:app
    container_name: famcy
    volumes:
      - ${FAMCY_SRC_FOLDER}:/app/.local/share/famcy/dev/console
      - static_volume:/app/.local/share/famcy/dev/venv/lib/python3.7/site-packages/Famcy/static/
    ports:
      - "6379:6379"
    expose:
      - 8888
  nginx:
    build: ./nginx-http
    volumes:
      - static_volume:/app/.local/share/famcy/dev/venv/lib/python3.7/site-packages/Famcy/static/
    ports:
      - 8888:80
    depends_on:
      - famcy

volumes:
  static_volume: