version: '3'
services:
  famcy:
    image: nexuni/famcy:1.0.beta.5
    command: 
      - bash
      - -c 
      - |
        cd /app/.local/share/famcy/dev && . venv/bin/activate && cd console
        pip3 install -r requirements.txt
        redis-server &
        cd /app/.local/share/famcy/dev/venv/lib/python3.7/site-packages 
        gunicorn -b 0.0.0.0:8888 Famcy.wsgi:app
    container_name: famcy
    volumes:
      - ${FAMCY_SRC_FOLDER}:/app/.local/share/famcy/dev/console
    ports:
      - "6379:6379"
    expose:
      - 8888
  nginx-proxy:
    container_name: nginx-proxy
    build: nginx-https
    restart: always
    ports:
      - 10443:10443
      - 1080:1080
    volumes:
      - static_volume:/app/.local/share/famcy/dev/venv/lib/python3.7/site-packages/Famcy/static/
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - famcy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  certs:
  html:
  vhost:
  acme: