FROM nexuni/ros2:foxy.desktop.beta.3.m1

COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install ffmpeg libsm6 libxslt-dev libxext6 redis-server python3.8-venv python3-pip -y
RUN pip3 install wheel uwsgi setuptools-rust
RUN pip3 install -r requirements.txt
RUN famcy init dev
RUN famcy deploy dev
RUN cd /root/.local/share/famcy/dev && . venv/bin/activate && pip3 install opencv-python

ENV PYTHONUNBUFFERED 1