version: '3'
services:
  famcy:
    image: nexuni/famcy:1.0.beta.5
    command: 
      - bash
      - -c 
      - |
        cd /app/.local/share/famcy/dev && . venv/bin/activate && cd console
        pip3 install -r requirements.txt
        redis-server &
        cd /app/.local/share/famcy/dev/venv/lib/python3.7/site-packages 
        gunicorn -b 0.0.0.0:8888 Famcy.wsgi:app
    container_name: famcy
    volumes:
      - ${FAMCY_SRC_FOLDER}:/app/.local/share/famcy/dev/console
    ports:
      - "8888:8888"
      - "6379:6379"
