version: '3'
services:
  famcy:
    image: nexuni/famcy:1.0.m1
    command: 
      - bash
      - -c 
      - |
        cd /app/.local/share/famcy/dev && . venv/bin/activate && cd console
        pip3 install famcy --upgrade
        pip3 install -r requirements.txt
        redis-server &
        famcy deploy dev
        cd /app/.local/share/famcy/dev/venv/lib/python3.7/site-packages/Famcy
        export FLASK_ENV=development
        export DEBUG=True
        python3 wsgi.py
    container_name: famcy
    volumes:
      - ${FAMCY_SRC_FOLDER}:/app/.local/share/famcy/dev/console
    ports:
      - "8888:8888"
      - "6379:6379"
